/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/6D EXPOSITOR ESPEJO.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano001.geometry}
        material={materials["Material.001"]}
        position={[-0.08, 0.02, -0.03]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano002.geometry}
        material={materials["Material.001"]}
        position={[0.13, 0.02, -0.04]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano003.geometry}
        material={materials["Material.001"]}
        position={[-0.08, 0.02, 0.13]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto.geometry}
        material={materials["Material.001"]}
        position={[0.23, -0.19, 0.07]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto001.geometry}
        material={materials["Material.001"]}
        position={[0.03, -0.19, 0.33]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto002.geometry}
        material={materials["Material.001"]}
        position={[0.2, 0.06, -0.12]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ3_ARD-geom"].geometry}
        material={materials.TQ3_ARD_front}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ3_ARD-geom_1"].geometry}
        material={materials.TQ3_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ3_ARD-geom_2"].geometry}
        material={materials.TQ3_ARD_edge}
      />
      <group rotation={[-Math.PI / 2, 1.13, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom001"].geometry}
          material={materials["TQ_ARD_front.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom001_1"].geometry}
          material={materials["TQ_ARD_back.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom001_2"].geometry}
          material={materials["TQ_ARD_edge.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ_ARD-geom"].geometry}
        material={materials.TQ_ARD_front}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ_ARD-geom_1"].geometry}
        material={materials.TQ_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ_ARD-geom_2"].geometry}
        material={materials.TQ_ARD_edge}
      />
    </group>
  );
}

useGLTF.preload("/6D EXPOSITOR ESPEJO.gltf");
